// Year 61 extra — updated answers
const questions = [
  {
    id: 'y61-q1', year: 61, questionNum: 1, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y61-p3.png',
    text: 'อะตอมหรือไอออนในข้อใดมีการจัดอิเล็กตรอนเหมือนกัน',
    choices: [' A 3919  A 4119  D 4020', 'E 35 17 E 3617 G 40 18', 'E 35 17  A 4119  D 4020', 'E 35 17 G 40 18  A 3919'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q3', year: 61, questionNum: 3, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y61-p3.png',
    text: 'เส้นสเปกตรัม 5 เส้น มีความยาวคลื่นดังนี้ A = 656 nm, B = 486 nm, C = 434 nm และ D = 410 nm การเปรียบเทียบเส้นสเปกตรัมในข้อใดถูกต้อง',
    choices: ['ความถี่ของเส้นสเปกตรัม A > B', 'พลังงานของเส้นสเปกตรัม C > B', 'เส้นสเปกตรัม A และ C มีพลังงานต่างกันเท่ากับ 434) (656 hc  J', 'เส้นสเปกตรัม D เกิดจากการที่อิเล็กตรอนมีการเปลี่ยนแปลงพลังงานน้อยที่สุดในกลุ่ม'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q4', year: 61, questionNum: 4, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y61-p3.png',
    text: 'ธาตุ X อยู่ในคาบที่ 2 ของตารางธาตุ ธาตุ Z มีจ านวนโปรตอนมากกว่าธาตุ X 6 โปรตอน ข้อใดถูกที่สุด',
    choices: ['ธาตุ X และธาตุ Z อยู่ในคาบเดียวกันในตารางธาตุ', 'ธาตุ Z มีจ านวนอิเล็กตรอนในระดับพลังงานที่สองมากกว่า 6', 'จ านวนอนุภาคมูลฐานในนิวเคลียสของธาตุ Z มากกว่าของธาตุ X 6 อนุภาค', 'จ านวนอิเล็กตรอนในระดับพลังงานนอกสุดของธาตุ Z มากกว่า ธาตุ X 6 อิเล็กตรอน'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q6', year: 61, questionNum: 6, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y61-p3.png',
    text: 'พิจารณาธาตุสมมุติต่อไปนี้ : 19L, 20M, 34Q, 35R, 37T ข้อใดผิดเกี่ยวกับการเปรียบเทียบค่าพลังงานไอออไนเซชันล าดับที่ 2 (IE2) ของธาตุ',
    choices: ['L น้อยกว่า M', 'M น้อยกว่า Q', 'Q น้อยกว่า R', 'R น้อยกว่า T'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q7', year: 61, questionNum: 7, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y61-p4.png',
    text: 'พิจารณาธาตุต่อไปนี้ : Na, Cl, Ca, Br การเปรียบเทียบขนาดของอะตอมและไอออนในข้อใดถูกต้อง',
    choices: ['Na > Na+ > Cl', 'Ca > Cl > Na+', 'Br– > Br > Ca', 'Br > Cl > Na'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q8', year: 61, questionNum: 8, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y61-p4.png',
    text: 'ข้อใดผิดเกี่ยวกับสมบัติของธาตุ X, T และ Z ซึ่งมีเลขอะตอม 15, 20 และ 33 ตามล าดับ',
    choices: ['ค่า IE1 ของ X > T > Z', 'ค่า EN ของ X > Z > T', 'ขนาดอะตอมของ T > Z > X', 'จุดหลอมเหลวของ T > Z > X'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q10', year: 61, questionNum: 10, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y61-p4.png',
    text: 'พิจารณาข้อมูลการทดลองต่อไปนี้ a. ชิ้นโลหะ M ท าปฏิกิริยากับธาตุ X ซึ่งเป็นของแข็งระเหิดง่าย ได้สารประกอบ Y ซึ่งละลายในน้ าได้ดี b. แบ่งสารละลายของ Y ในน้ ามาเติมน้ าคลอรีนและคาร์บอนเตตระคลอไรด์ (CCl4) แล้วเขย่า พบว่า ชั้น CCl4 มีสีชมพูแกมม่วง c. โลหะ M แทบไม่ท าปฏิกิริยากับน้ าที่อุณหภูมิห้อง แต่เมื',
    choices: ['สารประกอบ Y คือ MgI2', 'สารละลายของ X และของ Y ต่างก็มีสี', 'พลังงานไอออไนเซชันล าดับที่ 3 (IE3) ของ M มีค่าน้อยกว่าของ X', 'ถ้าเติมสารละลาย Na2SO4 ลงในสารละลายของ Y จะเกิดตะกอนสีขาว'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q11', year: 61, questionNum: 11, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y61-p4.png',
    text: 'ธาตุ D อยู่ในคาบที่สามของตารางธาตุ มีเลขออกซิเดชันได้หลายค่าตั้งแต่ –3 ถึง +5 ข้อใดสรุปได้ถูกต้องเกี่ยวกับธาตุนี้',
    choices: ['ปกติอยู่ในรูปโมเลกุล D2', 'ที่อุณหภูมิห้องอยู่ในสถานะแก๊ส', 'มีเลขออกซิเดชันเป็นค่าบวกเมื่ออยู่ในสารประกอบออกไซด์', 'เกิดสารประกอบคลอไรด์มากกว่า 1 ชนิด และเป็นสารมีขั้วทั้งหมด'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q12', year: 61, questionNum: 12, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y61-p4.png',
    text: 'เมื่อน าสารประกอบต่อไปนี้มาละลายในน้ าแยกกัน สารละลายในข้อใดมีสีทั้งคู่',
    choices: ['K2SO4, MnCl2', 'Cl2O, Co(NO3)2', 'K2Cr2O7, FeCl3', '[Ni(NH3)6]Cl2, RbCl'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q13', year: 61, questionNum: 13, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y61-p5.png',
    text: 'น าสารละลายของสาร A, B และ C มาแบ่งทดสอบโดยเติมสารละลาย NaCl, Na2CO3 และ Na2SO4 แยกกัน ได้ผลดังแสดงในตาราง สาร NaCl Na2CO3 Na2SO4 A ไม่เห็นการเปลี่ยนแปลง เกิดตะกอนขาว ไม่เห็นการเปลี่ยนแปลง B ไม่เห็นการเปลี่ยนแปลง ไม่เห็นการเปลี่ยนแปลง ไม่เห็นการเปลี่ยนแปลง C ไม่เห็นการเปลี่ยนแปลง เกิดตะกอนขาว เกิดตะ',
    choices: ['KNO3 MgCl2 BaCl2', 'Mg(NO3)2 Ba(NO3)2 KCl', 'BaCl2 KNO3 Mg(NO3)2', 'MgCl2 KCl Ba(NO3)2'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q16', year: 61, questionNum: 16, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y61-p5.png',
    text: 'เมื่อธาตุกัมมันตรังสี X เกิดการสลายตัว จะได้ไอโซโทปที่เสถียรของ Z โดยมีครึ่งชีวิต 20 วินาที ถ้าเริ่มต้นจาก ธาตุ X บริสุทธิ์ กราฟในข้อใดแสดงความสัมพันธ์ระหว่างมวล (m) ของ X กับเวลา (t) ได้ถูกต้อง',
    choices: ['', '', '', 'm t (s) m t (s) t (s) m m t (s)'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q18', year: 61, questionNum: 18, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y61-p5.png',
    text: 'พิจารณาธาตุที่มีสัญลักษณ์สมมุติต่อไปนี้ 7A 16D 20L 37M สารละลายในน้ าของออกไซด์ของธาตุใดที่สามารถเปลี่ยนสีฟีนอลฟ์ทาลีนจากไม่มีสีเป็นสีชมพู',
    choices: ['ธาตุ A และธาตุ D', 'ธาตุ A และธาตุ L', 'ธาตุ D และธาตุ M', 'ธาตุ L และธาตุ M'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q19', year: 61, questionNum: 19, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y61-p6.png',
    text: 'ธาตุ X เป็นของแข็งที่อุณหภูมิห้อง มีเลขอะตอมอยู่ในช่วง 19–36 ไม่ท าปฏิกิริยากับน้ า แต่ท าปฏิกิริยากับกรด ให้แก๊ส Y และสารละลายไม่มีสี ถ้า X 2 mol ท าปฏิกิริยาพอดีกับแก๊สคลอรีน 3 mol ได้สารประกอบคลอไรด์ ข้อสรุปใดผิด',
    choices: ['X อยู่หมู่ VA', 'X อยู่ในคาบที่ 4', 'แก๊ส Y ที่เกิดขึ้นคือไฮโดรเจน', 'X อยู่หมู่เดียวกับอะลูมิเนียม'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q20', year: 61, questionNum: 20, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y61-p6.png',
    text: 'ธาตุ M มีเลขอะตอม 37 สมการเคมีแสดงปฏิกิริยาที่เกี่ยวกับธาตุหรือสารประกอบของ M ข้อใดถูกต้อง',
    choices: ['M(s) + H2O(l) → 2MOH(aq) + H2(g)', 'M(s) + HCl(aq) → MCl2(aq) + H2(g)', 'MBr(aq) + I2(s) → MI(aq) + Br2(l)', 'M2SO4(aq) + BaCl2(aq) → ไม่เกิดปฏิกิริยา'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q21', year: 61, questionNum: 21, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y61-p6.png',
    text: 'ข้อใดถูกต้องเกี่ยวกับจ านวนพันธะและจ านวนอิเล็กตรอนคู่โดดเดี่ยวในสูตรโครงสร้างของ C2N2 โดยทุกอะตอม ในโมเลกุลเป็นไปตามกฎออกเตต จ านวน พันธะเดี่ยว พันธะคู่ พันธะสาม อิเล็กตรอนคู่โดดเดี่ยว (คู่)',
    choices: ['1 0 1 1', '1 0 2 2', '1 2 0 2', '2 1 2 2'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q22', year: 61, questionNum: 22, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y61-p6.png',
    text: 'สารประกอบ A เกิดจากการสร้างพันธะของธาตุที่มีเลขอะตอม 6 กับ 16 ส่วนสารประกอบ B เกิดจากธาตุที่มี เลขอะตอม 14 กับ 8 ข้อใดสรุปเกี่ยวกับสารประกอบ A และ B ถูกต้อง',
    choices: ['สารประกอบ A มีแรงยึดเหนี่ยวระหว่างโมเลกุลเป็นแรงดึงดูดระหว่างขั้ว', 'สารประกอบ A มีจุดหลอมเหลวและจุดเดือดสูงกว่าสารประกอบ B', 'สารประกอบ B ไม่ละลายน้ า แต่มีจุดหลอมเหลวและจุดเดือดสูง', 'สารประกอบ B สามารถละลายได้ดีในเฮกเซน'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q23', year: 61, questionNum: 23, topicId: 'thermochemistry',
    imageUrl: '/exam-images/y61-p6.png',
    text: 'ข้อที่ 23 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q24', year: 61, questionNum: 24, topicId: 'thermochemistry',
    imageUrl: '/exam-images/y61-p6.png',
    text: 'ข้อใดประกอบด้วยสารประกอบโคเวเลนต์ที่ละลายน้ าได้ดีทุกสาร',
    choices: ['กลูโคส เบนซีน น้ าแข็งแห้ง', 'เอทานอล ไฮโดรเจนฟลูออไรด์ กรดแอซีติก', 'กรดไฮโดรคลอริก คาร์บอนเตตระคลอไรด์ ซิลิคอนไดออกไซด์', 'คาร์บอนไดซัลไฟด์ ออกซิเจนไดฟลูออไรด์ แอมโมเนียมคลอไรด์'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q25', year: 61, questionNum: 25, topicId: 'thermochemistry',
    imageUrl: '/exam-images/y61-p7.png',
    text: 'ข้อที่ 25 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q26', year: 61, questionNum: 26, topicId: 'thermochemistry',
    imageUrl: '/exam-images/y61-p7.png',
    text: 'เมื่อน าสารผสมระหว่าง เอทานอล (CH3CH2OH) ไดเอทิลอีเทอร์ (CH3CH2OCH2CH3) และบิวเทน (CH3CH2CH2CH3) มากลั่นล าดับส่วน ล าดับของสารที่กลั่นออกมาเป็นดังข้อใด ล าดับที่ 1 ล าดับที่ 2 ล าดับที่ 3',
    choices: ['เอทานอล ไดเอทิลอีเทอร์ บิวเทน', 'ไดเอทิลอีเทอร์ บิวเทน เอทานอล', 'บิวเทน ไดเอทิลอีเทอร์ เอทานอล', 'บิวเทน เอทานอล ไดเอทิลอีเทอร์'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q27', year: 61, questionNum: 27, topicId: 'thermochemistry',
    imageUrl: '/exam-images/y61-p7.png',
    text: 'พิจารณาโมเลกุลหรือไอออนต่อไปนี้ : NO2, BF  4 , XeF4, CO  23 ข้อใดมีอะตอมกลางเป็นไปตามกฎออกเตตทั้งคู่',
    choices: ['NO2 และ BF  4', 'NO2 และ CO  23', 'BF  4 และ XeF4', 'BF  4 และ CO  23'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q28', year: 61, questionNum: 28, topicId: 'thermochemistry',
    imageUrl: '/exam-images/y61-p7.png',
    text: 'ข้อใดผิดเกี่ยวกับไอออน NH4+',
    choices: ['มีรูปร่างเป็นทรงสี่หน้า', 'ประกอบด้วยพันธะโคเวเลนต์มีขั้ว', 'อะตอมกลางไม่มีอิเล็กตรอนคู่โดดเดี่ยว', 'ความยาวพันธะ N–H 3 พันธะเหมือนกัน แต่แตกต่างจากพันธะที่สี่'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q29', year: 61, questionNum: 29, topicId: 'thermochemistry',
    imageUrl: '/exam-images/y61-p7.png',
    text: 'รูปร่างโมเลกุลในข้อใดแตกต่างจากข้ออื่น',
    choices: ['SO2', 'CO2', 'XeF2', 'BeCl2'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q30', year: 61, questionNum: 30, topicId: 'thermochemistry',
    imageUrl: '/exam-images/y61-p7.png',
    text: 'ถ้าพิจารณาเฉพาะมุมระหว่างพันธะที่เล็กที่สุดในโมเลกุลต่อไปนี้ มุมระหว่างพันธะของโมเลกุลใดมีค่าน้อยที่สุด',
    choices: ['NCl3', 'PCl5', 'SOCl2', 'CH2Cl2'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q31', year: 61, questionNum: 31, topicId: 'thermochemistry',
    imageUrl: '/exam-images/y61-p8.png',
    text: 'สารในข้อใดมีแรงยึดเหนี่ยวระหว่างโมเลกุลเป็นแรงระหว่างขั้วทั้งคู่',
    choices: ['PCl3 และ CO2', 'NH3 และ O2', 'CH4 และ SiH4', 'PH3 และ H2S'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 8 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q32', year: 61, questionNum: 32, topicId: 'thermochemistry',
    imageUrl: '/exam-images/y61-p8.png',
    text: 'ข้อที่ 32 (ดูรูปในหน้า 8)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(placeholder) ดูรูปในหน้า 8 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q33', year: 61, questionNum: 33, topicId: 'thermochemistry',
    imageUrl: '/exam-images/y61-p8.png',
    text: 'แก๊สไฮโดรเจนและแก๊สคลอรีนบรรจุในขวดปิดฝาที่ความดันและอุณหภูมิคงที่ หลังฉายแสงอัลตราไวโอเลต ปรากฏว่า แก๊สคลอรีนลดลงร้อยละ 25 โดยปริมาตร และแก๊สผสมในขวดประกอบด้วย แก๊สคลอรีน แก๊ส ไฮโดรเจน และแก๊สไฮโดรเจนคลอไรด์ ร้อยละ 30, 50 และ 20 โดยปริมาตร ตามล าดับ ข้อใดคือร้อยละโดย ปริมาตรของแก๊สไฮโดรเจนเมื่อตอนเ',
    choices: ['20', '40', '60', '80'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 8 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q38', year: 61, questionNum: 38, topicId: 'thermochemistry',
    imageUrl: '/exam-images/y61-p9.png',
    text: 'โลหะผสมประกอบด้วยอะลูมิเนียม สังกะสี ซิลิคอน และทองแดง ถ้าน าโลหะผสมนี้ 1000 mg มาละลายด้วย สารละลายกรดไฮโดรคลอริกมากเกินพอ จะเกิดแก๊สไฮโดรเจนปริมาตร 448 cm3 ที่ STP และมีของแข็ง เหลืออยู่ 350 mg ซึ่งประกอบด้วยซิลิคอนและทองแดง ข้อใดคือร้อยละโดยมวลของอะลูมิเนียมในโลหะผสม',
    choices: ['17.0', '24.9', '31.3', '36.4'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 9 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q39', year: 61, questionNum: 39, topicId: 'solutions',
    imageUrl: '/exam-images/y61-p9.png',
    text: 'ข้อที่ 39 (ดูรูปในหน้า 9)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(placeholder) ดูรูปในหน้า 9 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q41', year: 61, questionNum: 41, topicId: 'solutions',
    imageUrl: '/exam-images/y61-p9.png',
    text: 'โซเดียมเอไซด์ (NaN3) เป็นสารที่บรรจุในถุงลมนิรภัยในรถยนต์ แรงกระแทกเมื่อรถชนกันจะท าให้ NaN3 สลายตัวได้ผลิตภัณฑ์เป็นแก๊สไนโตรเจนและโลหะโซเดียม แก๊สไนโตรเจนที่เกิดขึ้นจะท าให้ถุงลมนิรภัยพองขึ้น อย่างรวดเร็ว และป้องกันไม่ให้ผู้ขับกระแทกกับพวงมาลัยรถ ส่วนโลหะโซเดียมอาจเกิดการระเบิดได้เมื่อสัมผัส กับควา',
    choices: ['39', '49', '52', '59'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 9 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q42', year: 61, questionNum: 42, topicId: 'solutions',
    imageUrl: '/exam-images/y61-p9.png',
    text: 'แร่ Trona มีสูตรเคมีเป็น Na2CO3NaHCO32H2O และมีมวลสูตรเท่ากับ 226 จะต้องใช้สารละลาย HCl เข้มข้น 0.125 mol/dm3 กี่ลูกบาศก์เซนติเมตร ในการเปลี่ยนคาร์บอเนตและไบคาร์บอเนตในตัวอย่างแร่ 0.452 g ไปเป็นคาร์บอนไดออกไซด์และน้ าอย่างสมบูรณ์ ก าหนดให้ HCO  3 (aq) + H+(aq) → CO2(g) + H2O(l) CO  23 (aq) + 2H+',
    choices: ['16.0', '32.0', '48.0', '64.0'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 9 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q48', year: 61, questionNum: 48, topicId: 'solutions',
    imageUrl: '/exam-images/y61-p10.png',
    text: 'ถ้าต้องการเตรียมสารละลายที่มีความเข้มข้นของไฮดรอกไซด์ไอออนเท่ากับ 0.4016 mol/dm3 ปริมาตร 500.0 cm3 โดยใช้สารละลาย Ba(OH)2 เข้มข้น 342 ppm ซึ่งมีความหนาแน่น 1.00 g/cm3 ปริมาตร 200.0 cm3 ผสมกับสารละลาย NaOH เข้มข้นร้อยละ 32.0 โดยมวล ซึ่งมีความหนาแน่น 1.25 g/cm3 แล้วจึงปรับ ปริมาตรของสารละลายเป็น 500 c',
    choices: ['2.05', '6.40', '20.0', '31.2'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 10 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q50', year: 61, questionNum: 50, topicId: 'solutions',
    imageUrl: '/exam-images/y61-p11.png',
    text: 'สารละลายในบีกเกอร์ที่ 1 คือ สารละลายของสาร M ในตัวท าละลาย A สารละลายนี้มีจุดเยือกแข็ง 2.0 oC สารละลายในบีกเกอร์ที่ 2 คือ สารละลายของสาร M ในตัวท าละลาย B ถ้ามวลของสาร M ในบีกเกอร์ทั้งสองเท่ากัน และมวลของตัวท าละลายในบีกเกอร์ทั้งสองเท่ากัน สารละลายใน บีกเกอร์ที่ 2 มีจุดเดือดเป็นกี่องศาเซลเซียส ก าหน',
    choices: ['61.0', '62.5', '63.5', '65.0'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 11 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q52', year: 61, questionNum: 52, topicId: 'solutions',
    imageUrl: '/exam-images/y61-p11.png',
    text: 'ข้อความใดผิด',
    choices: ['ในน้ าแข็งแห้ง โมเลกุลของคาร์บอนไดออกไซด์ยึดเหนี่ยวกันด้วยแรงดึงดูดระหว่างขั้ว', 'LiF(s) ประกอบด้วย Li+ ไอออนและ F– ไอออนยึดเหนี่ยวกันด้วยแรงดึงดูดระหว่างประจุไฟฟ้า', 'Kr(s) ประกอบด้วยอะตอมของคริปตอนซึ่งไม่มีขั้วยึดเหนี่ยวกันด้วยแรงลอนดอน มีสมบัติเหมือนผลึก โมเลกุล', 'พันธะระหว่างอะตอมของทองค าเกิดจากแรงยึดเหนี่ยวระหว่างเวเลนซ์อิเล็กตรอนที่เคลื่อนที่ได้อย่างอิสระ กับโปรตอนในนิวเคลียสทุก'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 11 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q53', year: 61, questionNum: 53, topicId: 'equilibrium',
    imageUrl: '/exam-images/y61-p11.png',
    text: 'พิจารณาสารต่อไปนี้ : C2H2, SiO2, CsI, W ข้อความใดผิด',
    choices: ['W น าไฟฟ้าเมื่อมีสถานะเป็นของแข็ง', 'C2H2 มีสถานะเป็นแก๊สที่อุณหภูมิห้อง', 'CsI ละลายในน้ า ได้สารละลายที่น าไฟฟ้าได้', 'SiO2 มีจุดหลอมเหลวสูงกว่า C2H2 เนื่องจาก SiO2 มีแรงยึดเหนี่ยวระหว่างโมเลกุลเป็นแรงดึงดูดระหว่างขั้ว'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 11 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q54', year: 61, questionNum: 54, topicId: 'equilibrium',
    imageUrl: '/exam-images/y61-p11.png',
    text: 'ข้อที่ 54 (ดูรูปในหน้า 11)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(placeholder) ดูรูปในหน้า 11 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q55', year: 61, questionNum: 55, topicId: 'equilibrium',
    imageUrl: '/exam-images/y61-p12.png',
    text: 'ที่อุณหภูมิ 25 oC สาร A, B และ C มีสถานะเป็นแก๊ส ของเหลว และของแข็ง ตามล าดับ จุดหลอมเหลวและจุดเดือดของสารทั้งสามในข้อใดเป็นไปได้ จุดเดือด (oC) จุดหลอมเหลว (oC) A B C A B C',
    choices: ['–42 98 330 –188 –91 40', '–42 330 98 –188 32 –91', '98 –42 330 –91 –8.8 40', '330 98 –42 32 –91 –188'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q56', year: 61, questionNum: 56, topicId: 'equilibrium',
    imageUrl: '/exam-images/y61-p12.png',
    text: 'ข้อที่ 56 (ดูรูปในหน้า 12)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(placeholder) ดูรูปในหน้า 12 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q57', year: 61, questionNum: 57, topicId: 'equilibrium',
    imageUrl: '/exam-images/y61-p12.png',
    text: 'ข้อใดถูกต้องเกี่ยวกับสมบัติของแก๊สตามทฤษฎีจลน์',
    choices: ['โมเลกุลของแก๊สอุดมคติมีขนาดเล็กมากจนถือได้ว่ามีมวลเป็นศูนย์', 'ที่อุณหภูมิเดียวกัน โมเลกุลของแก๊ส A และแก๊ส B จะมีพลังงานจลน์เฉลี่ยเท่ากันเสมอ', 'แก๊สทั่วไปจะมีสมบัติใกล้เคียงกับแก๊สอุดมคติมากที่สุด ถ้าอยู่ในภาวะที่มีความดันสูงและอุณหภูมิต่ า', 'ถ้าลดอุณหภูมิของแก๊สจาก 100 oC เป็น 50 oC โดยที่ปริมาตรคงที่ ความดันของแก๊สจะเพิ่มขึ้นเป็น 2 เท่า'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q58', year: 61, questionNum: 58, topicId: 'equilibrium',
    imageUrl: '/exam-images/y61-p12.png',
    text: 'พิจารณาไอของสารประกอบฟอสฟอรัสฟลูออไรด์สามชนิดคือ PF3, PF5 และ P2F4 ซึ่งมีสมบัติเป็นแก๊สอุดมคติ ไอของสารใดมีค่าความหนาแน่นเท่ากับ 4.60 g/L ที่ความดัน 0.82 atm และอุณหภูมิ 27 oC และถ้าปล่อยให้ ไอของสารทั้งสามชนิดผ่านท่อเล็ก ๆ ในสภาวะเดียวกัน ดังรูป ไอของสารใดแพร่จากจุด A ไปถึงจุด B ได้เร็วที่สุด สารที',
    choices: ['PF5 PF3', 'PF5 P2F4', 'P2F4 PF3', 'P2F4 P2F4 A B'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q59', year: 61, questionNum: 59, topicId: 'equilibrium',
    imageUrl: '/exam-images/y61-p12.png',
    text: 'แก๊สอุดมคติชนิดหนึ่ง มีความดัน 700 mmHg เมื่อปล่อยให้ฟุ้งกระจายที่อุณหภูมิเดิมจนกระทั่งความดันลดลง เป็น 200 mmHg อัตราส่วนระหว่างปริมาตรเดิมและปริมาตรใหม่เป็นเท่าใด',
    choices: ['0.29 : 1', '1 : 0.29', '1 : 3.5', '3.5 : 1'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 61',
  },
  {
    id: 'y61-q60', year: 61, questionNum: 60, topicId: 'equilibrium',
    imageUrl: '/exam-images/y61-p12.png',
    text: 'ฟองอากาศฟองหนึ่งมีปริมาตร 2.10 cm3 ลอยจากก้นทะเลสาบซึ่งมีอุณหภูมิ 10 oC และความดัน 5.66 atm ขึ้นมายังผิวน้ าซึ่งมีอุณหภูมิ 27 oC และความดัน 1.00 atm ฟองอากาศนี้จะมีปริมาตรสุดท้ายเป็นกี่ลูกบาศก์ เซนติเมตร',
    choices: ['4.40', '11.2', '12.6', '32.1 ส่วนที่ II. ข้อสอบอัตนัยแบบเขียนตอบ จ านวน 15 ข้อ ข้อละ 2 คะแนน รวม 30 คะแนน จงเขียนค าตอบลงในช่องว่างที่ก าหนดให้ใ'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 61',
  },
];
module.exports = questions;
