// Year 60 extra — updated answers
const questions = [
  {
    id: 'y60-q1', year: 60, questionNum: 1, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y60-p3.png',
    text: 'หลอดรังสีแคโทดที่เจาะรูตรงกลางขั้วแคโทดและแอโนด หลังขั้วแคโทดและแอโนดมีฉากเรืองแสง ก และ ข ตามล าดับ ภายในหลอดบรรจุแก๊ส 1 ชนิด และมีความดันต ่า เมื่อผ่านกระแสไฟฟ้า เข้าไปในหลอด จะเกิดจุดบนฉากเรืองแสงหลังขั้วทั้งสอง ดังรูป ข้อความใดถูกต้อง',
    choices: ['อนุภาค X มีอ านาจในการทะลุทะลวงสูง สามารถทะลุผ่านแผ่นตะกั่วบาง ๆ ได้', 'อนุภาค X และ Y มีค่าประจุต่อมวล (e/m) คงที่ ไม่ขึ้นกับชนิดของแก๊สในหลอด', 'อนุภาค X และ Y เป็นไอออนบวกและไอออนลบของธาตุที่เป็นองค์ประกอบของแก๊ส ที่บรรจุในหลอด', 'แต่ละอนุภาค X ในหลอดที่บรรจุแก๊ส H2 มีมวลมากกว่ามวลของแต่ละอนุภาค Y ใน หลอดที่บรรจุแก๊ส He'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q4', year: 60, questionNum: 4, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y60-p3.png',
    text: 'ธาตุ A และ B เป็นไอโซโทปกัน A มีจ านวนนิวตรอนน้อยกว่า B 5 นิวตรอน เมื่อกลายเป็น B2 จะมีจ านวนอิเล็กตรอนและนิวตรอนเท่ากับ 10 และ 15 ตามล าดับ ข้อใดเป็นสัญลักษณ์นิวเคลียร์ของธาตุ A',
    choices: ['A 18 8', 'A 22 12', 'A 25 10', 'A 25 15'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q7', year: 60, questionNum: 7, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y60-p4.png',
    text: 'ข้อใดเป็นอะตอมหรือไอออนที่มีจ านวนอิเล็กตรอนเดี่ยวในสถานะพื้นเท่ากัน',
    choices: ['Cr+ และ Mn2+', 'As และ Mn2+', 'Cu2+ และ Cr3+', 'As3+ และ Cu'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q8', year: 60, questionNum: 8, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y60-p4.png',
    text: 'ก าหนดให้ สารประกอบคลอไรด์ของธาตุ A มีสูตรเป็น ACl2 มีลักษณะเป็นของแข็งสีขาว ไม่น าไฟฟ้า ละลายน ้าได้สารละลายที่เป็นกลางและน าไฟฟ้าได้ สมบัติของธาตุ A ข้อใดถูกต้อง',
    choices: ['A เป็นธาตุอโลหะ', 'A เป็นธาตุที่อยู่ในคาบที่ 2 ของตารางธาตุ', 'A เป็นธาตุที่อยู่หมู่เดียวกับธาตุที่มีเลขอะตอมเท่ากับ 26', 'ไอออน A2+ มีการจัดเรียงอิเล็กตรอนเหมือนแก๊สมีตระกูล'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q9', year: 60, questionNum: 9, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y60-p4.png',
    text: 'พิจารณาสูตรเคมีของสารประกอบ ต่อไปนี้ [Co(NH3)4SO4]Cl HClO4 และ Na[Au(CN)2] เลขออกซิเดชันของธาตุที่ขีดเส้นใต้ในสารประกอบ ข้อใดถูกต้อง เลขออกซิเดชันของธาตุที่ขีดเส้นใต้ [Co(NH3)4SO4]Cl HClO4 Na[Au(CN)2]',
    choices: ['+2 +6 +3', '+2 +7 +3', '+6 +6 +1', '+6 +7 +1'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q10', year: 60, questionNum: 10, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y60-p4.png',
    text: 'พิจารณา การบรรจุอิเล็กตรอน แบบ A, B, C และ D ต่อไปนี้ ข้อความใดถูกต้อง',
    choices: ['แบบ A เป็นของอะตอมที่มีค่าอิเล็กโทรเนกาติวิตีมากที่สุด', 'แบบ B เป็นการบรรจุอิเล็กตรอนที่ไม่เป็นไปตามกฎของฮุนด์', 'แบบ C เป็นการบรรจุอิเล็กตรอนที่ไม่เป็นไปตามหลักการกีดกันของเพาลี', 'แบบ D เป็นของอะตอมที่เสถียรและมีค่าพลังงานไอออไนเซชันล าดับที่ 1 มากที่สุด'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q11', year: 60, questionNum: 11, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y60-p4.png',
    text: 'ก าหนดให้ ธาตุ A, D, E และ G มีการจัดเรียงอิเล็กตรอนที่สถานะพื้น ดังนี้ A : [He] 2s2 2p4 D : [Ne] 3s2 3p3 E : [Ar] 3d10 4s2 4p1 G : [Ar] 3d10 4s2 4p3 การเปรียบเทียบขนาดอะตอมและพลังงานไอออไนเซชันล าดับที่ 1 ข้อใดถูกต้อง ขนาดอะตอม พลังงานไอออไนเซชันล าดับที่ 1',
    choices: ['G > E > D A > D > E', 'D > G > A E > G > A', 'A > E > G D > G > A', 'E > G > A G > A > E'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q13', year: 60, questionNum: 13, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p5.png',
    text: 'ข้อใดเป็นสารประกอบออกไซด์ที่ท าปฏิกิริยากับน ้าแล้วได้สารละลายที่เปลี่ยนสีกระดาษ ลิตมัสจากน ้าเงินเป็นแดง',
    choices: ['P4O10 และ Cr2O3', 'Cl2O7 และ P4O10', 'Cr2O3 และ Na2O', 'Cl2O7 และ Na2O'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q14', year: 60, questionNum: 14, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p5.png',
    text: 'เมื่อผสมสารละลายที่ประกอบด้วยไอออน Ba2+, Mg2+, Na+, Cl–, SO4 2– และ HPO4 2– เข้าด้วยกัน พบว่ามีตะกอน เกิดขึ้น สูตรเคมีของสารประกอบแต่ละชนิดที่เป็นตะกอนซึ่งเกิดจากการผสมสารละลายของไอออนดังกล่าว ข้อใดถูกต้อง',
    choices: ['Na2SO4, MgCl2, BaCl2', 'Na2HPO4, Na2SO4, MgCl2', 'BaSO4, MgSO4, MgHPO4', 'MgHPO4, BaSO4, BaHPO4'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q15', year: 60, questionNum: 15, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p5.png',
    text: 'ข้อที่ 15 (ดูรูปในหน้า 5)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q16', year: 60, questionNum: 16, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p5.png',
    text: 'พิจารณาสมการของปฏิกิริยานิวเคลียร์ต่อไปนี้ Co 5927 + A  Mn 56 25 + รังสีแอลฟา Te 130 52 + B  I 130 53 + 2 นิวตรอน Rn 222 86 + รังสีแอลฟา  C + รังสีแกมมา ข้อใดเป็น A, B และ C ตามล าดับ',
    choices: ['นิวตรอน ดิวทีรอน และ Ra 226 88', 'นิวตรอน โปรตอน และ Ac 226 89', 'โปรตอน ดิวทีรอน และ Rn 225 86', 'รังสีบีตา รังสีแอลฟา และ Fr 224 87'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q17', year: 60, questionNum: 17, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p5.png',
    text: 'ข้อใดเป็นสมบัติของธาตุไฮโดรเจนที่ต่างจากธาตุหมู่ VIIA',
    choices: ['มีเลขออกซิเดชันได้มากกว่า 1 ค่า', 'มีค่าอิเล็กโทรเนกาติวิตีมากกว่า 2', 'มีจ านวนเวเลนซ์อิเล็กตรอนเท่ากับ 1', 'ในธรรมชาติอยู่ในรูปโมเลกุลอะตอมคู่'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q20', year: 60, questionNum: 20, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p6.png',
    text: 'ข้อที่ 20 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q21', year: 60, questionNum: 21, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p6.png',
    text: 'ข้อที่ 21 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q22', year: 60, questionNum: 22, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p6.png',
    text: 'ข้อใดเป็นสารที่มีรูปร่างโมเลกุลเหมือนกัน',
    choices: ['BF4  และ ICl4 ', 'TeCl4 และ POCl3', 'ICl4  และ TeCl4', 'BF4  และ POCl3'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q23', year: 60, questionNum: 23, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p6.png',
    text: 'ข้อใดเป็นสารประกอบที่มีมุมระหว่างพันธะแคบที่สุด',
    choices: ['ClF3', 'SiF4', 'NCl3', 'OCl2'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q24', year: 60, questionNum: 24, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p6.png',
    text: 'ข้อที่ 24 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q25', year: 60, questionNum: 25, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p7.png',
    text: 'ข้อที่ 25 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q26', year: 60, questionNum: 26, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p7.png',
    text: 'ข้อที่ 26 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q27', year: 60, questionNum: 27, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p7.png',
    text: 'ข้อที่ 27 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q28', year: 60, questionNum: 28, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p7.png',
    text: 'ข้อที่ 28 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q29', year: 60, questionNum: 29, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p7.png',
    text: 'ข้อที่ 29 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q30', year: 60, questionNum: 30, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p7.png',
    text: 'ข้อที่ 30 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q31', year: 60, questionNum: 31, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p8.png',
    text: 'ข้อที่ 31 (ดูรูปในหน้า 8)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 8 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q32', year: 60, questionNum: 32, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p8.png',
    text: 'ข้อใดทั้ง 2 โมเลกุลเป็นโมเลกุลที่มีขั้ว',
    choices: ['HCN และ KrF4', 'AsI5 และ SBr2', 'ClH3 และ TeF4', 'SO3 และ PBr3'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 8 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q33', year: 60, questionNum: 33, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p8.png',
    text: 'ข้อที่ 33 (ดูรูปในหน้า 8)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 8 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q34', year: 60, questionNum: 34, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p8.png',
    text: 'ข้อที่ 34 (ดูรูปในหน้า 8)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 8 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q35', year: 60, questionNum: 35, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y60-p8.png',
    text: 'ข้อที่ 35 (ดูรูปในหน้า 8)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 8 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q42', year: 60, questionNum: 42, topicId: 'states-of-matter',
    imageUrl: '/exam-images/y60-p9.png',
    text: 'ข้อที่ 42 (ดูรูปในหน้า 9)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 9 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q43', year: 60, questionNum: 43, topicId: 'states-of-matter',
    imageUrl: '/exam-images/y60-p10.png',
    text: 'ข้อที่ 43 (ดูรูปในหน้า 10)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 10 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q47', year: 60, questionNum: 47, topicId: 'solutions',
    imageUrl: '/exam-images/y60-p10.png',
    text: 'ข้อที่ 47 (ดูรูปในหน้า 10)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 10 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q48', year: 60, questionNum: 48, topicId: 'solutions',
    imageUrl: '/exam-images/y60-p10.png',
    text: 'ข้อที่ 48 (ดูรูปในหน้า 10)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 10 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q49', year: 60, questionNum: 49, topicId: 'solutions',
    imageUrl: '/exam-images/y60-p11.png',
    text: 'ข้อที่ 49 (ดูรูปในหน้า 11)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 11 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q50', year: 60, questionNum: 50, topicId: 'solutions',
    imageUrl: '/exam-images/y60-p11.png',
    text: 'ข้อที่ 50 (ดูรูปในหน้า 11)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 11 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q51', year: 60, questionNum: 51, topicId: 'solutions',
    imageUrl: '/exam-images/y60-p11.png',
    text: 'ข้อที่ 51 (ดูรูปในหน้า 11)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 11 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q53', year: 60, questionNum: 53, topicId: 'solutions',
    imageUrl: '/exam-images/y60-p11.png',
    text: 'ข้อที่ 53 (ดูรูปในหน้า 11)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 11 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q56', year: 60, questionNum: 56, topicId: 'solutions',
    imageUrl: '/exam-images/y60-p12.png',
    text: 'ข้อที่ 56 (ดูรูปในหน้า 12)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q57', year: 60, questionNum: 57, topicId: 'solutions',
    imageUrl: '/exam-images/y60-p12.png',
    text: 'ข้อที่ 57 (ดูรูปในหน้า 12)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q58', year: 60, questionNum: 58, topicId: 'solutions',
    imageUrl: '/exam-images/y60-p12.png',
    text: 'ข้อที่ 58 (ดูรูปในหน้า 12)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 60',
  },
  {
    id: 'y60-q59', year: 60, questionNum: 59, topicId: 'solutions',
    imageUrl: '/exam-images/y60-p12.png',
    text: 'เมื่อผสมสารละลาย CaCl2 เข้มข้น 1.00 mol/dm3 ปริมาตร 20.0 cm3 กับสารละลาย CaCl2 เข้มข้น 0.200 mol/dm3 ปริมาตร 60.0 cm3 แล้วเติมน ้าปรับปริมาตรสารละลายเป็น 100 cm3 ความเข้มข้นของสารในสารละลายผสมนี้ ข้อใดถูกต้อง สาร ความเข้มข้น',
    choices: ['Ca2+ 0.032 mol/dm3', 'Cl– 0.800 mol/dm3', 'Ca2+ Cl– 2.42 % (w/v)', 'CaCl2 35.5 g/dm3'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 60',
  },
];
module.exports = questions;
