// Year 64 extra — updated answers
const questions = [
  {
    id: 'y64-q1', year: 64, questionNum: 1, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y64-p3.png',
    text: 'ข้อที่ 1 (ดูรูปในหน้า 3)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q2', year: 64, questionNum: 2, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y64-p3.png',
    text: 'ข้อที่ 2 (ดูรูปในหน้า 3)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q3', year: 64, questionNum: 3, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y64-p3.png',
    text: 'ข้อที่ 3 (ดูรูปในหน้า 3)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q4', year: 64, questionNum: 4, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y64-p3.png',
    text: 'ข้อที่ 4 (ดูรูปในหน้า 3)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q5', year: 64, questionNum: 5, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y64-p3.png',
    text: 'ข้อที่ 5 (ดูรูปในหน้า 3)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q6', year: 64, questionNum: 6, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y64-p3.png',
    text: 'ข้อที่ 6 (ดูรูปในหน้า 3)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q7', year: 64, questionNum: 7, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y64-p4.png',
    text: 'ข้อที่ 7 (ดูรูปในหน้า 4)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q8', year: 64, questionNum: 8, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y64-p4.png',
    text: 'ข้อที่ 8 (ดูรูปในหน้า 4)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q9', year: 64, questionNum: 9, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y64-p4.png',
    text: 'ข้อที่ 9 (ดูรูปในหน้า 4)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q10', year: 64, questionNum: 10, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y64-p4.png',
    text: 'ข้อที่ 10 (ดูรูปในหน้า 4)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q11', year: 64, questionNum: 11, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y64-p4.png',
    text: 'ข้อที่ 11 (ดูรูปในหน้า 4)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q12', year: 64, questionNum: 12, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y64-p4.png',
    text: 'ข้อที่ 12 (ดูรูปในหน้า 4)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q13', year: 64, questionNum: 13, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y64-p5.png',
    text: 'ข้อที่ 13 (ดูรูปในหน้า 5)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q14', year: 64, questionNum: 14, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y64-p5.png',
    text: 'ข้อที่ 14 (ดูรูปในหน้า 5)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q15', year: 64, questionNum: 15, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y64-p5.png',
    text: 'ข้อที่ 15 (ดูรูปในหน้า 5)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q16', year: 64, questionNum: 16, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y64-p5.png',
    text: 'ข้อที่ 16 (ดูรูปในหน้า 5)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q17', year: 64, questionNum: 17, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y64-p5.png',
    text: 'ข้อที่ 17 (ดูรูปในหน้า 5)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q18', year: 64, questionNum: 18, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y64-p5.png',
    text: 'ข้อที่ 18 (ดูรูปในหน้า 5)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q19', year: 64, questionNum: 19, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y64-p6.png',
    text: 'ข้อที่ 19 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q20', year: 64, questionNum: 20, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y64-p6.png',
    text: 'ข้อที่ 20 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q21', year: 64, questionNum: 21, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y64-p6.png',
    text: 'ข้อที่ 21 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q22', year: 64, questionNum: 22, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y64-p6.png',
    text: 'ข้อที่ 22 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q23', year: 64, questionNum: 23, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y64-p6.png',
    text: 'ข้อที่ 23 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q24', year: 64, questionNum: 24, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y64-p6.png',
    text: 'ข้อที่ 24 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q25', year: 64, questionNum: 25, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y64-p7.png',
    text: 'ข้อที่ 25 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q26', year: 64, questionNum: 26, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y64-p7.png',
    text: 'ข้อที่ 26 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q27', year: 64, questionNum: 27, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y64-p7.png',
    text: 'ข้อที่ 27 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q28', year: 64, questionNum: 28, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y64-p7.png',
    text: 'ข้อที่ 28 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q29', year: 64, questionNum: 29, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y64-p7.png',
    text: 'ข้อที่ 29 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q30', year: 64, questionNum: 30, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y64-p7.png',
    text: 'ข้อที่ 30 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q36', year: 64, questionNum: 36, topicId: 'stoichiometry',
    imageUrl: '/exam-images/y64-p8.png',
    text: 'ข้อที่ 36 (ดูรูปในหน้า 8)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 8 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q39', year: 64, questionNum: 39, topicId: 'stoichiometry',
    imageUrl: '/exam-images/y64-p9.png',
    text: 'ข้อที่ 39 (ดูรูปในหน้า 9)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 9 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q43', year: 64, questionNum: 43, topicId: 'stoichiometry',
    imageUrl: '/exam-images/y64-p10.png',
    text: 'ข้อที่ 43 (ดูรูปในหน้า 10)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 10 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q45', year: 64, questionNum: 45, topicId: 'stoichiometry',
    imageUrl: '/exam-images/y64-p10.png',
    text: 'ข้อที่ 45 (ดูรูปในหน้า 10)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 10 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q46', year: 64, questionNum: 46, topicId: 'solutions',
    imageUrl: '/exam-images/y64-p10.png',
    text: 'ข้อที่ 46 (ดูรูปในหน้า 10)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 10 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q47', year: 64, questionNum: 47, topicId: 'solutions',
    imageUrl: '/exam-images/y64-p10.png',
    text: 'ข้อที่ 47 (ดูรูปในหน้า 10)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 10 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q50', year: 64, questionNum: 50, topicId: 'solutions',
    imageUrl: '/exam-images/y64-p11.png',
    text: 'ข้อที่ 50 (ดูรูปในหน้า 11)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 11 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q52', year: 64, questionNum: 52, topicId: 'solutions',
    imageUrl: '/exam-images/y64-p11.png',
    text: 'ข้อที่ 52 (ดูรูปในหน้า 11)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 11 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q53', year: 64, questionNum: 53, topicId: 'solutions',
    imageUrl: '/exam-images/y64-p11.png',
    text: 'ข้อที่ 53 (ดูรูปในหน้า 11)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 11 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q54', year: 64, questionNum: 54, topicId: 'solutions',
    imageUrl: '/exam-images/y64-p11.png',
    text: 'ข้อที่ 54 (ดูรูปในหน้า 11)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 11 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q56', year: 64, questionNum: 56, topicId: 'solutions',
    imageUrl: '/exam-images/y64-p12.png',
    text: 'ข้อที่ 56 (ดูรูปในหน้า 12)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q57', year: 64, questionNum: 57, topicId: 'solutions',
    imageUrl: '/exam-images/y64-p12.png',
    text: 'ข้อที่ 57 (ดูรูปในหน้า 12)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 64',
  },
  {
    id: 'y64-q58', year: 64, questionNum: 58, topicId: 'solutions',
    imageUrl: '/exam-images/y64-p12.png',
    text: 'ข้อที่ 58 (ดูรูปในหน้า 12)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 64',
  },
];
module.exports = questions;
