// Year 65 extra — updated answers
const questions = [
  {
    id: 'y65-q1', year: 65, questionNum: 1, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y65-p3.png',
    text: 'ข้อที่ 1 (ดูรูปในหน้า 3)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q3', year: 65, questionNum: 3, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y65-p3.png',
    text: 'ข้อที่ 3 (ดูรูปในหน้า 3)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q4', year: 65, questionNum: 4, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y65-p3.png',
    text: 'ข้อที่ 4 (ดูรูปในหน้า 3)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q5', year: 65, questionNum: 5, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y65-p3.png',
    text: 'ข้อที่ 5 (ดูรูปในหน้า 3)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q6', year: 65, questionNum: 6, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y65-p3.png',
    text: 'ข้อที่ 6 (ดูรูปในหน้า 3)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 3 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q7', year: 65, questionNum: 7, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y65-p4.png',
    text: 'ข้อที่ 7 (ดูรูปในหน้า 4)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q8', year: 65, questionNum: 8, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y65-p4.png',
    text: 'ข้อที่ 8 (ดูรูปในหน้า 4)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q9', year: 65, questionNum: 9, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y65-p4.png',
    text: 'ข้อที่ 9 (ดูรูปในหน้า 4)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q10', year: 65, questionNum: 10, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y65-p4.png',
    text: 'ข้อที่ 10 (ดูรูปในหน้า 4)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q11', year: 65, questionNum: 11, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y65-p4.png',
    text: 'ข้อที่ 11 (ดูรูปในหน้า 4)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q12', year: 65, questionNum: 12, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y65-p4.png',
    text: 'ข้อที่ 12 (ดูรูปในหน้า 4)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 4 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q13', year: 65, questionNum: 13, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y65-p5.png',
    text: 'ข้อที่ 13 (ดูรูปในหน้า 5)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q14', year: 65, questionNum: 14, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y65-p5.png',
    text: 'ข้อที่ 14 (ดูรูปในหน้า 5)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q15', year: 65, questionNum: 15, topicId: 'atomic-structure',
    imageUrl: '/exam-images/y65-p5.png',
    text: 'ข้อที่ 15 (ดูรูปในหน้า 5)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q16', year: 65, questionNum: 16, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y65-p5.png',
    text: 'ข้อที่ 16 (ดูรูปในหน้า 5)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q17', year: 65, questionNum: 17, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y65-p5.png',
    text: 'ข้อที่ 17 (ดูรูปในหน้า 5)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q18', year: 65, questionNum: 18, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y65-p5.png',
    text: 'ข้อที่ 18 (ดูรูปในหน้า 5)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 5 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q19', year: 65, questionNum: 19, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y65-p6.png',
    text: 'ข้อที่ 19 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q20', year: 65, questionNum: 20, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y65-p6.png',
    text: 'ข้อที่ 20 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q21', year: 65, questionNum: 21, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y65-p6.png',
    text: 'ข้อที่ 21 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q22', year: 65, questionNum: 22, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y65-p6.png',
    text: 'ข้อที่ 22 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q23', year: 65, questionNum: 23, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y65-p6.png',
    text: 'ข้อที่ 23 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q24', year: 65, questionNum: 24, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y65-p6.png',
    text: 'ข้อที่ 24 (ดูรูปในหน้า 6)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 6 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q25', year: 65, questionNum: 25, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y65-p7.png',
    text: 'ข้อที่ 25 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q26', year: 65, questionNum: 26, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y65-p7.png',
    text: 'ข้อที่ 26 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q27', year: 65, questionNum: 27, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y65-p7.png',
    text: 'ข้อที่ 27 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q28', year: 65, questionNum: 28, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y65-p7.png',
    text: 'ข้อที่ 28 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q29', year: 65, questionNum: 29, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y65-p7.png',
    text: 'ข้อที่ 29 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q30', year: 65, questionNum: 30, topicId: 'chemical-bonding',
    imageUrl: '/exam-images/y65-p7.png',
    text: 'ข้อที่ 30 (ดูรูปในหน้า 7)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 7 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q31', year: 65, questionNum: 31, topicId: 'stoichiometry',
    imageUrl: '/exam-images/y65-p8.png',
    text: 'ข้อที่ 31 (ดูรูปในหน้า 8)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 8 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q35', year: 65, questionNum: 35, topicId: 'stoichiometry',
    imageUrl: '/exam-images/y65-p8.png',
    text: 'ข้อที่ 35 (ดูรูปในหน้า 8)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 8 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q36', year: 65, questionNum: 36, topicId: 'stoichiometry',
    imageUrl: '/exam-images/y65-p8.png',
    text: 'ข้อที่ 36 (ดูรูปในหน้า 8)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 8 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q37', year: 65, questionNum: 37, topicId: 'stoichiometry',
    imageUrl: '/exam-images/y65-p9.png',
    text: 'ข้อที่ 37 (ดูรูปในหน้า 9)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 9 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q38', year: 65, questionNum: 38, topicId: 'stoichiometry',
    imageUrl: '/exam-images/y65-p9.png',
    text: 'ข้อที่ 38 (ดูรูปในหน้า 9)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 9 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q39', year: 65, questionNum: 39, topicId: 'stoichiometry',
    imageUrl: '/exam-images/y65-p9.png',
    text: 'ข้อที่ 39 (ดูรูปในหน้า 9)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 9 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q40', year: 65, questionNum: 40, topicId: 'stoichiometry',
    imageUrl: '/exam-images/y65-p9.png',
    text: 'ข้อที่ 40 (ดูรูปในหน้า 9)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 9 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q41', year: 65, questionNum: 41, topicId: 'stoichiometry',
    imageUrl: '/exam-images/y65-p9.png',
    text: 'ข้อที่ 41 (ดูรูปในหน้า 9)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 9 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q43', year: 65, questionNum: 43, topicId: 'stoichiometry',
    imageUrl: '/exam-images/y65-p10.png',
    text: 'ข้อที่ 43 (ดูรูปในหน้า 10)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 10 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q45', year: 65, questionNum: 45, topicId: 'stoichiometry',
    imageUrl: '/exam-images/y65-p10.png',
    text: 'ข้อที่ 45 (ดูรูปในหน้า 10)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 10 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q46', year: 65, questionNum: 46, topicId: 'solutions',
    imageUrl: '/exam-images/y65-p10.png',
    text: 'ข้อที่ 46 (ดูรูปในหน้า 10)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 10 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q47', year: 65, questionNum: 47, topicId: 'solutions',
    imageUrl: '/exam-images/y65-p10.png',
    text: 'ข้อที่ 47 (ดูรูปในหน้า 10)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 10 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q48', year: 65, questionNum: 48, topicId: 'solutions',
    imageUrl: '/exam-images/y65-p10.png',
    text: 'ข้อที่ 48 (ดูรูปในหน้า 10)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 10 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q49', year: 65, questionNum: 49, topicId: 'solutions',
    imageUrl: '/exam-images/y65-p11.png',
    text: 'ข้อที่ 49 (ดูรูปในหน้า 11)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 11 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q51', year: 65, questionNum: 51, topicId: 'solutions',
    imageUrl: '/exam-images/y65-p11.png',
    text: 'ข้อที่ 51 (ดูรูปในหน้า 11)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 11 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q52', year: 65, questionNum: 52, topicId: 'solutions',
    imageUrl: '/exam-images/y65-p11.png',
    text: 'ข้อที่ 52 (ดูรูปในหน้า 11)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 11 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q53', year: 65, questionNum: 53, topicId: 'solutions',
    imageUrl: '/exam-images/y65-p11.png',
    text: 'ข้อที่ 53 (ดูรูปในหน้า 11)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 11 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q57', year: 65, questionNum: 57, topicId: 'solutions',
    imageUrl: '/exam-images/y65-p12.png',
    text: 'ข้อที่ 57 (ดูรูปในหน้า 12)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 0,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q58', year: 65, questionNum: 58, topicId: 'solutions',
    imageUrl: '/exam-images/y65-p12.png',
    text: 'ข้อที่ 58 (ดูรูปในหน้า 12)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 1,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q59', year: 65, questionNum: 59, topicId: 'solutions',
    imageUrl: '/exam-images/y65-p12.png',
    text: 'ข้อที่ 59 (ดูรูปในหน้า 12)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 2,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 65',
  },
  {
    id: 'y65-q60', year: 65, questionNum: 60, topicId: 'solutions',
    imageUrl: '/exam-images/y65-p12.png',
    text: 'ข้อที่ 60 (ดูรูปในหน้า 12)',
    choices: ['ก', 'ข', 'ค', 'ง'],
    correctIndex: 3,
    explanation: '(verified) ดูรูปในหน้า 12 ของข้อสอบปี 65',
  },
];
module.exports = questions;
