// Adapter that exposes past-exam questions as practiceable `Question`s.
// Kept separate from pastExamQuestions.ts because that file is regenerated by gen_questions.js.
import { Question } from './questions'
import {
  pastExamQuestions,
  PastExamQuestion,
  getExamQuestionsByYear,
} from './pastExamQuestions'

// A past-exam question is answerable in-app only if it doesn't depend on a missing
// figure and has a real answer key.
export function isAnswerable(q: PastExamQuestion): boolean {
  const imageProvided = !!q.imageUrl
  return (!q.requiresImage || imageProvided) && q.correctIndex >= 0
}

function toQuestion(q: PastExamQuestion): Question {
  return {
    id: q.id,
    topicId: q.topicId,
    text: q.text,
    choices: q.choices,
    correctIndex: q.correctIndex,
    explanation: q.explanation ?? '',
    difficulty: 'hard',
    hasMath: true,
    imageUrl: q.imageUrl,
  }
}

/** Past-exam questions for a topic, ready to feed the quiz runner. */
export function getExamPracticeByTopic(topicId: string): Question[] {
  return pastExamQuestions
    .filter((q) => q.topicId === topicId && isAnswerable(q))
    .map(toQuestion)
}

/** Answerable past-exam questions for a given B.E. year, ordered by question number. */
export function getExamPracticeByYear(year: number): Question[] {
  return getExamQuestionsByYear(year)
    .filter(isAnswerable)
    .sort((a, b) => a.questionNum - b.questionNum)
    .map(toQuestion)
}

/** Count of answerable questions per year, for showing availability in the UI. */
export function getAnswerableCountByYear(): Record<number, number> {
  const map: Record<number, number> = {}
  for (const q of pastExamQuestions) {
    if (isAnswerable(q)) map[q.year] = (map[q.year] ?? 0) + 1
  }
  return map
}
